// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCustomGame(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function AddGameFromPCGW(arg1:main.UserGameSelection):Promise<void>;

export function CreateBackup(arg1:string):Promise<void>;

export function GetBackupHistory(arg1:string):Promise<Array<main.BackupInfo>>;

export function GetConfig():Promise<main.BackupConfig>;

export function GetDefaultBackupPath():Promise<string>;

export function GetGameInfo(arg1:string):Promise<main.GameInfo>;

export function GetGameList():Promise<Array<main.GameInfo>>;

export function RemoveGame(arg1:string):Promise<void>;

export function ScanGames():Promise<main.ScanResult>;

export function SearchGamesOnPCGW(arg1:string):Promise<Array<main.GameSearchResult>>;

export function SetBackupPath(arg1:string):Promise<void>;

export function UpdateConfig(arg1:main.BackupConfig):Promise<void>;

export function ValidateGamePaths(arg1:string):Promise<Record<string, Array<string>>>;

export function ValidatePath(arg1:string):Promise<boolean>;
