// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCustomGame(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddCustomGame'](arg1, arg2, arg3);
}

export function AddGameFromPCGW(arg1) {
  return window['go']['main']['App']['AddGameFromPCGW'](arg1);
}

export function CreateBackup(arg1) {
  return window['go']['main']['App']['CreateBackup'](arg1);
}

export function GetBackupHistory(arg1) {
  return window['go']['main']['App']['GetBackupHistory'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDefaultBackupPath() {
  return window['go']['main']['App']['GetDefaultBackupPath']();
}

export function GetGameInfo(arg1) {
  return window['go']['main']['App']['GetGameInfo'](arg1);
}

export function GetGameList() {
  return window['go']['main']['App']['GetGameList']();
}

export function RemoveGame(arg1) {
  return window['go']['main']['App']['RemoveGame'](arg1);
}

export function ScanGames() {
  return window['go']['main']['App']['ScanGames']();
}

export function SearchGamesOnPCGW(arg1) {
  return window['go']['main']['App']['SearchGamesOnPCGW'](arg1);
}

export function SetBackupPath(arg1) {
  return window['go']['main']['App']['SetBackupPath'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function ValidateGamePaths(arg1) {
  return window['go']['main']['App']['ValidateGamePaths'](arg1);
}

export function ValidatePath(arg1) {
  return window['go']['main']['App']['ValidatePath'](arg1);
}
